/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as CaregiverIndexRouteImport } from './routes/caregiver.index'
import { Route as PatientRemindersRouteImport } from './routes/patient.reminders'
import { Route as PatientRecognizeRouteImport } from './routes/patient.recognize'
import { Route as PatientHelpRouteImport } from './routes/patient.help'
import { Route as CaregiverStatsRouteImport } from './routes/caregiver.stats'
import { Route as CaregiverSettingsRouteImport } from './routes/caregiver.settings'
import { Route as CaregiverRemindersRouteImport } from './routes/caregiver.reminders'
import { Route as CaregiverPinRouteImport } from './routes/caregiver.pin'
import { Route as CaregiverContactRouteImport } from './routes/caregiver.contact'
import { Route as CaregiverQrIndexRouteImport } from './routes/caregiver.qr.index'
import { Route as PatientStepsIdRouteImport } from './routes/patient.steps.$id'
import { Route as CaregiverQrNewRouteImport } from './routes/caregiver.qr.new'
import { Route as CaregiverQrIdRouteImport } from './routes/caregiver.qr.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverIndexRoute = CaregiverIndexRouteImport.update({
  id: '/caregiver/',
  path: '/caregiver/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRemindersRoute = PatientRemindersRouteImport.update({
  id: '/patient/reminders',
  path: '/patient/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRecognizeRoute = PatientRecognizeRouteImport.update({
  id: '/patient/recognize',
  path: '/patient/recognize',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHelpRoute = PatientHelpRouteImport.update({
  id: '/patient/help',
  path: '/patient/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverStatsRoute = CaregiverStatsRouteImport.update({
  id: '/caregiver/stats',
  path: '/caregiver/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverSettingsRoute = CaregiverSettingsRouteImport.update({
  id: '/caregiver/settings',
  path: '/caregiver/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRemindersRoute = CaregiverRemindersRouteImport.update({
  id: '/caregiver/reminders',
  path: '/caregiver/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverPinRoute = CaregiverPinRouteImport.update({
  id: '/caregiver/pin',
  path: '/caregiver/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverContactRoute = CaregiverContactRouteImport.update({
  id: '/caregiver/contact',
  path: '/caregiver/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverQrIndexRoute = CaregiverQrIndexRouteImport.update({
  id: '/caregiver/qr/',
  path: '/caregiver/qr/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientStepsIdRoute = PatientStepsIdRouteImport.update({
  id: '/patient/steps/$id',
  path: '/patient/steps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverQrNewRoute = CaregiverQrNewRouteImport.update({
  id: '/caregiver/qr/new',
  path: '/caregiver/qr/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverQrIdRoute = CaregiverQrIdRouteImport.update({
  id: '/caregiver/qr/$id',
  path: '/caregiver/qr/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caregiver/contact': typeof CaregiverContactRoute
  '/caregiver/pin': typeof CaregiverPinRoute
  '/caregiver/reminders': typeof CaregiverRemindersRoute
  '/caregiver/settings': typeof CaregiverSettingsRoute
  '/caregiver/stats': typeof CaregiverStatsRoute
  '/patient/help': typeof PatientHelpRoute
  '/patient/recognize': typeof PatientRecognizeRoute
  '/patient/reminders': typeof PatientRemindersRoute
  '/caregiver/': typeof CaregiverIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/caregiver/qr/$id': typeof CaregiverQrIdRoute
  '/caregiver/qr/new': typeof CaregiverQrNewRoute
  '/patient/steps/$id': typeof PatientStepsIdRoute
  '/caregiver/qr/': typeof CaregiverQrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caregiver/contact': typeof CaregiverContactRoute
  '/caregiver/pin': typeof CaregiverPinRoute
  '/caregiver/reminders': typeof CaregiverRemindersRoute
  '/caregiver/settings': typeof CaregiverSettingsRoute
  '/caregiver/stats': typeof CaregiverStatsRoute
  '/patient/help': typeof PatientHelpRoute
  '/patient/recognize': typeof PatientRecognizeRoute
  '/patient/reminders': typeof PatientRemindersRoute
  '/caregiver': typeof CaregiverIndexRoute
  '/patient': typeof PatientIndexRoute
  '/caregiver/qr/$id': typeof CaregiverQrIdRoute
  '/caregiver/qr/new': typeof CaregiverQrNewRoute
  '/patient/steps/$id': typeof PatientStepsIdRoute
  '/caregiver/qr': typeof CaregiverQrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caregiver/contact': typeof CaregiverContactRoute
  '/caregiver/pin': typeof CaregiverPinRoute
  '/caregiver/reminders': typeof CaregiverRemindersRoute
  '/caregiver/settings': typeof CaregiverSettingsRoute
  '/caregiver/stats': typeof CaregiverStatsRoute
  '/patient/help': typeof PatientHelpRoute
  '/patient/recognize': typeof PatientRecognizeRoute
  '/patient/reminders': typeof PatientRemindersRoute
  '/caregiver/': typeof CaregiverIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/caregiver/qr/$id': typeof CaregiverQrIdRoute
  '/caregiver/qr/new': typeof CaregiverQrNewRoute
  '/patient/steps/$id': typeof PatientStepsIdRoute
  '/caregiver/qr/': typeof CaregiverQrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caregiver/contact'
    | '/caregiver/pin'
    | '/caregiver/reminders'
    | '/caregiver/settings'
    | '/caregiver/stats'
    | '/patient/help'
    | '/patient/recognize'
    | '/patient/reminders'
    | '/caregiver/'
    | '/patient/'
    | '/caregiver/qr/$id'
    | '/caregiver/qr/new'
    | '/patient/steps/$id'
    | '/caregiver/qr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caregiver/contact'
    | '/caregiver/pin'
    | '/caregiver/reminders'
    | '/caregiver/settings'
    | '/caregiver/stats'
    | '/patient/help'
    | '/patient/recognize'
    | '/patient/reminders'
    | '/caregiver'
    | '/patient'
    | '/caregiver/qr/$id'
    | '/caregiver/qr/new'
    | '/patient/steps/$id'
    | '/caregiver/qr'
  id:
    | '__root__'
    | '/'
    | '/caregiver/contact'
    | '/caregiver/pin'
    | '/caregiver/reminders'
    | '/caregiver/settings'
    | '/caregiver/stats'
    | '/patient/help'
    | '/patient/recognize'
    | '/patient/reminders'
    | '/caregiver/'
    | '/patient/'
    | '/caregiver/qr/$id'
    | '/caregiver/qr/new'
    | '/patient/steps/$id'
    | '/caregiver/qr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaregiverContactRoute: typeof CaregiverContactRoute
  CaregiverPinRoute: typeof CaregiverPinRoute
  CaregiverRemindersRoute: typeof CaregiverRemindersRoute
  CaregiverSettingsRoute: typeof CaregiverSettingsRoute
  CaregiverStatsRoute: typeof CaregiverStatsRoute
  PatientHelpRoute: typeof PatientHelpRoute
  PatientRecognizeRoute: typeof PatientRecognizeRoute
  PatientRemindersRoute: typeof PatientRemindersRoute
  CaregiverIndexRoute: typeof CaregiverIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  CaregiverQrIdRoute: typeof CaregiverQrIdRoute
  CaregiverQrNewRoute: typeof CaregiverQrNewRoute
  PatientStepsIdRoute: typeof PatientStepsIdRoute
  CaregiverQrIndexRoute: typeof CaregiverQrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/': {
      id: '/caregiver/'
      path: '/caregiver'
      fullPath: '/caregiver/'
      preLoaderRoute: typeof CaregiverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/reminders': {
      id: '/patient/reminders'
      path: '/patient/reminders'
      fullPath: '/patient/reminders'
      preLoaderRoute: typeof PatientRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/recognize': {
      id: '/patient/recognize'
      path: '/patient/recognize'
      fullPath: '/patient/recognize'
      preLoaderRoute: typeof PatientRecognizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/help': {
      id: '/patient/help'
      path: '/patient/help'
      fullPath: '/patient/help'
      preLoaderRoute: typeof PatientHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/stats': {
      id: '/caregiver/stats'
      path: '/caregiver/stats'
      fullPath: '/caregiver/stats'
      preLoaderRoute: typeof CaregiverStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/settings': {
      id: '/caregiver/settings'
      path: '/caregiver/settings'
      fullPath: '/caregiver/settings'
      preLoaderRoute: typeof CaregiverSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/reminders': {
      id: '/caregiver/reminders'
      path: '/caregiver/reminders'
      fullPath: '/caregiver/reminders'
      preLoaderRoute: typeof CaregiverRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/pin': {
      id: '/caregiver/pin'
      path: '/caregiver/pin'
      fullPath: '/caregiver/pin'
      preLoaderRoute: typeof CaregiverPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/contact': {
      id: '/caregiver/contact'
      path: '/caregiver/contact'
      fullPath: '/caregiver/contact'
      preLoaderRoute: typeof CaregiverContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/qr/': {
      id: '/caregiver/qr/'
      path: '/caregiver/qr'
      fullPath: '/caregiver/qr/'
      preLoaderRoute: typeof CaregiverQrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/steps/$id': {
      id: '/patient/steps/$id'
      path: '/patient/steps/$id'
      fullPath: '/patient/steps/$id'
      preLoaderRoute: typeof PatientStepsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/qr/new': {
      id: '/caregiver/qr/new'
      path: '/caregiver/qr/new'
      fullPath: '/caregiver/qr/new'
      preLoaderRoute: typeof CaregiverQrNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/qr/$id': {
      id: '/caregiver/qr/$id'
      path: '/caregiver/qr/$id'
      fullPath: '/caregiver/qr/$id'
      preLoaderRoute: typeof CaregiverQrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaregiverContactRoute: CaregiverContactRoute,
  CaregiverPinRoute: CaregiverPinRoute,
  CaregiverRemindersRoute: CaregiverRemindersRoute,
  CaregiverSettingsRoute: CaregiverSettingsRoute,
  CaregiverStatsRoute: CaregiverStatsRoute,
  PatientHelpRoute: PatientHelpRoute,
  PatientRecognizeRoute: PatientRecognizeRoute,
  PatientRemindersRoute: PatientRemindersRoute,
  CaregiverIndexRoute: CaregiverIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  CaregiverQrIdRoute: CaregiverQrIdRoute,
  CaregiverQrNewRoute: CaregiverQrNewRoute,
  PatientStepsIdRoute: PatientStepsIdRoute,
  CaregiverQrIndexRoute: CaregiverQrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
